#pragma once

#ifndef COMMANDS_H_INCLUDED
#define COMMANDS_H_INCLUDED

#include <DXP.Interfaces.h>

using namespace DXP;

void Command_CTMHelloWorld(IServerDocumentView* const View, std::wstring* Parameters);
//Autogenerated code. Commands definition. End

#endif //COMMANDS_H_INCLUDED
