#include "stdafx.h"
#include "Commands.h"

//Autogenerated code. Commands implementation. Begin

void Command_CTMHelloWorld(IServerDocumentView* const View, std::wstring* Parameters)
{
	MessageBoxA(NULL, "Hello world", "Warning", MB_OK);
	return;
}
//Autogenerated code. Commands implementation. End

