#include "stdafx.h"
#include "Main.h"
#include "Commands.h"
#include "DXP.Classes.h"
#include "DXP.Interfaces.h"


using namespace DXP;

/*.................................................................................................*/
// The server methods and fields are inherited from the
// TServerModule class in EDPClasses unit.
class CCTMHelloWorld : public CServerModule
{
protected:
    IServerDocument * NewDocumentInstance(const wstring AKind, const wstring AFileName);    //Override;
public:
    void InitializeCommands();                                                              //Override;
    CCTMHelloWorld(IClient * const AClient, const wstring AName);
};
/*.................................................................................................*/

/*.................................................................................................*/
CCTMHelloWorld::CCTMHelloWorld(IClient * const AClient, const wstring AName)
    : CServerModule(AClient, AName) 
{}
/*.................................................................................................*/

/*.................................................................................................*/
// This is where Commands (process launchers) are initialized and stored.
void CCTMHelloWorld::InitializeCommands()
{
    //Autogenerated code. Commands registration. Begin
    mCommandLauncher->RegisterCommand(L"CTMHelloWorld", Command_CTMHelloWorld);
    //Autogenerated code. Commands registration. End
}
/*.................................................................................................*/

/*.................................................................................................*/
IServerDocument * CCTMHelloWorld::NewDocumentInstance(const wstring AKind, const wstring AFileName)
{
    return nullptr;
}
/*.................................................................................................*/

/*.................................................................................................*/
// This is where a server module is created from the PluginFactory call.
// The new server module sets up the command launcher table which stores commands (processes).
HRESULT _stdcall PluginFactory(IClient * const AClient, IDispatch * * pAServerMoudle)
{
    // name of server passed in should have the same name as specified in INS file
    CCTMHelloWorld * pCTMHelloWorld = new CCTMHelloWorld(AClient, L"CTMHelloWorld");

    pCTMHelloWorld->Initialize();

    pCTMHelloWorld->QueryInterface(IID_IDispatch, (void **)pAServerMoudle);

    return S_OK;
}
/*.................................................................................................*/
